CITIES_IN_ROMANIA = [
    "Bucharest",
    "Cluj-Napoca",
    "Timișoara",
    "Iași",
    "Constanța",
    "Craiova",
    "Brașov",
    "Galați",
    "Oradea",
    "Ploiești",
    "Brăila",
    "Arad",
    "Pitești",
    "Sibiu",
    "Bacău",
    "Târgu Mureș",
    "Baia Mare",
    "Buzău",
    "Satu Mare",
    "Botoșani",
    "Râmnicu Vâlcea",
    "Suceava",
    "Focșani",
    "Târgoviște",
    "Tulcea",
    "Deva",
    "Reșița",
    "Slatina",
    "Giurgiu",
    "Târgu Jiu",
    "Hunedoara",
    "Roman",
    "Zalău",
    "Sfântu Gheorghe",
    "Călărași",
    "Alba Iulia",
    "Piatra Neamț",
    "Vaslui",
    "Făgăraș",
    "Turda",
    "Mediaș",
    "Sighetu Marmației",
    "Miercurea Ciuc",
    "Gheorgheni",
    "Bistrița",
    "Blaj",
    "Caracal",
    "Cugir",
    "Lugoj",
    "Petrila",
    "Motru",
    "Sebeș",
    "Odorheiu Secuiesc",
    "Lupeni",
    "Vulcan",
    "Panciu",
    "Onești",
    "Gura Humorului",
    "Toplița",
    "Baia Sprie",
    "Beiuș",
    "Câmpia Turzii",
    "Râșnov",
    "Zărnești",
    "Mioveni",
    "Buftea",
    "Caransebeș",
    "Cisnădie",
    "Comănești",
    "Curtea de Argeș",
    "Darabani",
    "Dorohoi",
    "Dragomirești",
    "Hârlău",
    "Jibou",
    "Luduș",
    "Marghita",
    "Năsăud",
    "Ocna Mureș",
    "Pecica",
    "Săcele",
    "Săliște",
    "Sângeorgiu de Pădure",
    "Tecuci",
    "Tismana",
    "Turtucaia",
    "Vicovu de Sus",
]

DIRECTIONS = ["NE", "SE", "SW", "NW", "S", "N", "E", "W"]

OPERATORS = [">", "<", "==", ">=", "=<"]

# This data is from Romania - 2022
HIGHEST_TEMPERATURE_IN_ROMANIA = 39
LOWEST_TEMPERATURE_IN_ROMANIA = -22

HIGHEST_RAINFALL_VALUE_IN_ROMANIA = 1.1
LOWEST_RAINFALL_VALUE_IN_ROMANIA = 0.3

LOWEST_WIND_SPEED_IN_ROMANIA = 1
HIGHEST_WIND_SPEED_IN_ROMANIA = 80
